### PR TITLE
Add html_content option for form email tempaltes

### PR DESCRIPTION
**Pull request by sekoskel**
An email template may contain html, in order to render it properly we must set correct content type for an email

Refs MH-50

### CODE REVIEW

**Comment by akx** [comment]
Hmm. I'm kinda not sure if we want to start doing migrations and everything in our fork... Could we... like, auto-detect if the template is HTML? Like, look for at least one opening and closing HTML tag in it? Not sure if that's sane.

**Comment by sekoskel** [comment]
Then this approach wouldn't be different from hardcoding content type to html. Plain text messages look plaintexty even if message's content type is html.

**Comment by akx** [comment]
Detecting at least one `<[^>]+>` and one `</[^>]+>` is less false-positive prone though than just making everything HTML, it feels like.

I don't know. I just feel like if we start doing migrations and all, this is becoming more of an actual fork of the (abandoned?) original version than just a bugfix fork...

**Comment by sekoskel** [comment]
ok, lets close this.

**Pull request closed without merging**
